services:
  hapi-fhir-jpaserver:
    build: .
    container_name: hapi-fhir-jpaserver
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - test-network
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    networks:
      - test-network
volumes:
  hapi-fhir-postgres:
networks:
  test-network:
    external: true
